### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Blugori** [D0CTOR-ZED/FloorMats#2]
Hi !
I got an issue while testing FloorMats.

Minecraft : 1.16.3
Forge : 34.1.33
FloorMats : 1.1.0

![image](https://user-images.githubusercontent.com/66573974/97750357-e87e5a00-1af0-11eb-942b-ce0fd1c2de9f.png)

Best regards

**Comment by D0CTOR-ZED** [comment]
You appear to be using the 1.15.2 version with Minecraft 1.16.3.  Please try using the 1.16.3 version.  Thanks for trying my mod.
