### ISSUE TITLE
Crash with Immersive Engineering and Forge version 36.1.10 or higher

### ISSUE THREAD

**Issue by ghost** [D0CTOR-ZED/FloorMats#4]
Hello,

Updating Forge to version 36.1.10 or higher seems to break Floor Mats' version check for Immersive Engineering:

> Mod File: floormats-1.16.5-v1.3.0.jar
	Failure message: Mod floormats only supports immersiveengineering 4.0.1 or above
		Currently, immersiveengineering is 1.16.5-4.2.4-134
	Mod Version: 1.16.5-v1.3.0

This pack I'm working on loaded perfectly fine with Forge 36.1.6 but started crashing after I updated to Forge 36.1.12 (no other changes were made). Downgrading back to Forge 36.1.9 allowed the pack to load again. I'm assuming that this change to Forge is the cause: https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.1.10/forge-1.16.5-36.1.10-changelog.txt

Here is a full crash log as well in case it is useful: https://pastebin.com/qeG7Ffzx

Let me know if I can provide any additional information.

**Comment by D0CTOR-ZED** [comment]
Thank you for the info.  I've fixed the issue and uploaded v1.3.1 to curseforge.  You should be able to find it here once it has been approved: https://www.curseforge.com/minecraft/mc-mods/floor-mats/files/3290411

**Comment by ghost** [comment]
Confirmed that v1.3.1 works correctly and allows my modpack to load using the latest Forge.

Thanks so much!
