### ISSUE TITLE
1.18 Non-gilded floor mats don't send redstone signal

### ISSUE THREAD

**Issue by Marutzo** [D0CTOR-ZED/FloorMats#7]
I'm on 1.18 and normal floor mats triggered by everything and not just players, don't seem to send any redstone signal. Only by combining gilded with normal ones can I get it to trigger a lamp like this:
![image](https://user-images.githubusercontent.com/69410159/156521503-9485b8d7-0616-474b-bfbb-4311827c3607.png)

**Comment by D0CTOR-ZED** [comment]
Wow.  Sorry about that.  Fixed for 1.18.1.  Thank you very much for bringing that to my attention.

**Comment by Marutzo** [comment]
Great work! Thank you for the speedy fix.
