### ISSUE TITLE
Broken mineable/axe.json tag

### ISSUE THREAD

**Issue by brisingraerowing** [D0CTOR-ZED/FloorMats#8]
If IE isn't installed, the tag fails to load as the IE entries are not listed as optional. This breaks axes in game.

**Comment by ranenvious** [comment]
for me even with Immersive Engineering installed axes are broken.

**Comment by D0CTOR-ZED** [comment]
Which version is this for?

**Comment by brisingraerowing** [comment]
1.19.2.

**Comment by D0CTOR-ZED** [comment]
Fixed the bug.  Sorry about the delay.
